apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-iscsi-nfs-install
  labels:
    app: longhorn-iscsi-nfs-install
spec:
  selector:
    matchLabels:
      app: longhorn-iscsi-nfs-install
  template:
    metadata:
      labels:
        app: longhorn-iscsi-nfs-install
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: longhorn-iscsi-nfs-install
        image: docker.io/mddamato/longhorn-iscsi-nfs-utils:v0
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /mount
            name: kubeconfig
          - mountPath: /etc/yum.repos.d
            name: yum
      containers:
      - name: sleep
        image: k8s.gcr.io/pause:3.1
      volumes:
        - name: kubeconfig
          hostPath:
            path: /var/lib/rancher/hostMount/longhorn-iscsi-nfs-install
        - name: yum
          hostPath:
            path: /etc/yum.repos.d




